/* Auto-generated by psvita-toolkit from decompiled/apk_jadx/sources -- FalsoJNI callback candidates. */
/* Every entry here is a CANDIDATE: confirm the method belongs on the .so's actual call path, and */
/* read the real Java implementation (jadx) before trusting the stub body. See docs/dev-notes/jni_analyzer.md. */
#pragma once
#include <stdarg.h>
#include <falso_jni/FalsoJNI_Impl.h>

extern jint stub_GLMediaPlayer_getMusicDuration_0(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_getSoundDuration_1(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_getSoundStatus_2(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_init_3(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isMediaPlaying_4(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isMusicPlaying_5(jmethodID id, va_list args);
extern jint stub_GLMediaPlayer_isSoundLoaded_6(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadMusic_7(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_loadSound_8(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseAllMusic_9(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseAllSounds_10(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseMusic_11(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_pauseSound_12(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_playMusic_13(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_playSound_14(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resetSound_15(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeMusic_16(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_resumeSound_17(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_setVolume_18(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopAllMusic_19(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopAllSounds_20(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopMusic_21(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_stopSound_22(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_unloadMusic_23(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_unloadSound_24(jmethodID id, va_list args);
extern void stub_GLMediaPlayer_updateSound_25(jmethodID id, va_list args);
extern void stub_GLResLoader_destroy_26(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getRawResource_27(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceBytes_28(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceFull_29(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getResourceFull_30(jmethodID id, va_list args);
extern jint stub_GLResLoader_getResourceLength_31(jmethodID id, va_list args);
extern jobject stub_GLResLoader_getString_32(jmethodID id, va_list args);
extern void stub_GLResLoader_init_33(jmethodID id, va_list args);
extern jobject stub_Device_Device_34(jmethodID id, va_list args);
extern void stub_Device_InitDeviceValues_35(jmethodID id, va_list args);
extern jboolean stub_Device_IsWifiEnable_36(jmethodID id, va_list args);
extern jobject stub_Device_ValidateStringforURL_37(jmethodID id, va_list args);
extern jobject stub_Device_a_38(jmethodID id, va_list args);
extern jobject stub_Device_b_39(jmethodID id, va_list args);
extern jobject stub_Device_c_40(jmethodID id, va_list args);
extern jint stub_Device_createUniqueCode_41(jmethodID id, va_list args);
extern jobject stub_Device_d_42(jmethodID id, va_list args);
extern void stub_Device_e_43(jmethodID id, va_list args);
extern jobject stub_Device_f_44(jmethodID id, va_list args);
extern jobject stub_Device_getCarrier_45(jmethodID id, va_list args);
extern jobject stub_Device_getDemoCode_46(jmethodID id, va_list args);
extern jobject stub_Device_getDevice_47(jmethodID id, va_list args);
extern jobject stub_Device_getHostName_48(jmethodID id, va_list args);
extern jobject stub_Device_getIMEI_49(jmethodID id, va_list args);
extern jboolean stub_Device_getIsRoaming_50(jmethodID id, va_list args);
extern jobject stub_Device_getLanguage_51(jmethodID id, va_list args);
extern jobject stub_Device_getLineNumber_52(jmethodID id, va_list args);
extern jobject stub_Device_getNetworkCountryIso_53(jmethodID id, va_list args);
extern jobject stub_Device_getNetworkOperator_54(jmethodID id, va_list args);
extern jobject stub_Device_getNetworkOperatorName_55(jmethodID id, va_list args);
extern jobject stub_Device_getPhoneModel_56(jmethodID id, va_list args);
extern jobject stub_Device_getSimCountryIso_57(jmethodID id, va_list args);
extern jobject stub_Device_getSimOperator_58(jmethodID id, va_list args);
extern jobject stub_Device_getSimOperatorName_59(jmethodID id, va_list args);
extern jint stub_Device_getUniqueCode_60(jmethodID id, va_list args);
extern jobject stub_Device_getUserAgent_61(jmethodID id, va_list args);
extern void stub_Device_init_62(jmethodID id, va_list args);
extern void stub_Device_a_63(jmethodID id, va_list args);
extern jobject stub_GameGLSurfaceView_GameGLSurfaceView_64(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_checkEglError_65(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_onSizeChanged_66(jmethodID id, va_list args);
extern jboolean stub_GameGLSurfaceView_onTouchEvent_67(jmethodID id, va_list args);
extern void stub_GameGLSurfaceView_onWindowFocusChanged_68(jmethodID id, va_list args);
extern jobject stub_GameRenderer_GameRenderer_69(jmethodID id, va_list args);
extern void stub_GameRenderer_onDrawFrame_70(jmethodID id, va_list args);
extern void stub_GameRenderer_onSurfaceChanged_71(jmethodID id, va_list args);
extern void stub_GameRenderer_onSurfaceCreated_72(jmethodID id, va_list args);
extern void stub_ShadowGuardian_Exit_73(jmethodID id, va_list args);
extern jlong stub_ShadowGuardian_GetCurrentTime_74(jmethodID id, va_list args);
extern jint stub_ShadowGuardian_GetPhoneLanguage_75(jmethodID id, va_list args);
extern void stub_ShadowGuardian_Pause_76(jmethodID id, va_list args);
extern void stub_ShadowGuardian_d_77(jmethodID id, va_list args);
extern jobject stub_ShadowGuardian_da_78(jmethodID id, va_list args);
extern jobject stub_ShadowGuardian_db_79(jmethodID id, va_list args);
extern jobject stub_ShadowGuardian_dc_80(jmethodID id, va_list args);
extern void stub_ShadowGuardian_enableWifi_81(jmethodID id, va_list args);
extern jint stub_ShadowGuardian_getManufacture_82(jmethodID id, va_list args);
extern jboolean stub_ShadowGuardian_isNeedGcOnFrame_83(jmethodID id, va_list args);
extern jint stub_ShadowGuardian_isWifiEnabled_84(jmethodID id, va_list args);
extern void stub_ShadowGuardian_launchGLLive_85(jmethodID id, va_list args);
extern void stub_ShadowGuardian_launchIGP_86(jmethodID id, va_list args);
extern void stub_ShadowGuardian_notifyTrophy_87(jmethodID id, va_list args);
extern void stub_ShadowGuardian_openBrowser_88(jmethodID id, va_list args);
extern void stub_ShadowGuardian_sendAppToBackground_89(jmethodID id, va_list args);
extern void stub_ShadowGuardian_sendTrackingInfo_90(jmethodID id, va_list args);
extern void stub_ShadowGuardian_onAccuracyChanged_91(jmethodID id, va_list args);
extern void stub_ShadowGuardian_onCreate_92(jmethodID id, va_list args);
extern void stub_ShadowGuardian_onDestroy_93(jmethodID id, va_list args);
extern jboolean stub_ShadowGuardian_onKeyDown_94(jmethodID id, va_list args);
extern jboolean stub_ShadowGuardian_onKeyLongPress_95(jmethodID id, va_list args);
extern jboolean stub_ShadowGuardian_onKeyUp_96(jmethodID id, va_list args);
extern void stub_ShadowGuardian_onLowMemory_97(jmethodID id, va_list args);
extern void stub_ShadowGuardian_onPause_98(jmethodID id, va_list args);
extern void stub_ShadowGuardian_onRestart_99(jmethodID id, va_list args);
extern void stub_ShadowGuardian_onResume_100(jmethodID id, va_list args);
extern jboolean stub_ShadowGuardian_onSearchRequested_101(jmethodID id, va_list args);
extern void stub_ShadowGuardian_onSensorChanged_102(jmethodID id, va_list args);
extern void stub_ShadowGuardian_onStart_103(jmethodID id, va_list args);
extern void stub_ShadowGuardian_onStop_104(jmethodID id, va_list args);

// Candidate NameToMethodID entries -- append into the real nameToMethodId[] in java.c
static const NameToMethodID generated_nameToMethodId[] = {
    { 0, "getMusicDuration", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 1, "getSoundDuration", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 2, "getSoundStatus", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 3, "init", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 4, "isMediaPlaying", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 5, "isMusicPlaying", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 6, "isSoundLoaded", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 7, "loadMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 8, "loadSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 9, "pauseAllMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 10, "pauseAllSounds", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 11, "pauseMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 12, "pauseSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 13, "playMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 14, "playSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 15, "resetSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 16, "resumeMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 17, "resumeSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 18, "setVolume", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 19, "stopAllMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 20, "stopAllSounds", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 21, "stopMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 22, "stopSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 23, "unloadMusic", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 24, "unloadSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 25, "updateSound", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer
    { 26, "destroy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader
    { 27, "getRawResource", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader
    { 28, "getResourceBytes", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader
    { 29, "getResourceFull", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader
    { 30, "getResourceFull", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader
    { 31, "getResourceLength", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader
    { 32, "getString", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader
    { 33, "init", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader
    { 34, "Device", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 35, "InitDeviceValues", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 36, "IsWifiEnable", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 37, "ValidateStringforURL", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 38, "a", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 39, "b", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 40, "c", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 41, "createUniqueCode", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 42, "d", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 43, "e", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 44, "f", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 45, "getCarrier", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 46, "getDemoCode", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 47, "getDevice", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 48, "getHostName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 49, "getIMEI", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 50, "getIsRoaming", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 51, "getLanguage", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 52, "getLineNumber", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 53, "getNetworkCountryIso", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 54, "getNetworkOperator", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 55, "getNetworkOperatorName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 56, "getPhoneModel", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 57, "getSimCountryIso", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 58, "getSimOperator", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 59, "getSimOperatorName", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 60, "getUniqueCode", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 61, "getUserAgent", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 62, "init", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 63, "a", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device
    { 64, "GameGLSurfaceView", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView
    { 65, "checkEglError", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView
    { 66, "onSizeChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView
    { 67, "onTouchEvent", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView
    { 68, "onWindowFocusChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView
    { 69, "GameRenderer", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.GameRenderer
    { 70, "onDrawFrame", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GameRenderer
    { 71, "onSurfaceChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GameRenderer
    { 72, "onSurfaceCreated", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.GameRenderer
    { 73, "Exit", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 74, "GetCurrentTime", METHOD_TYPE_LONG },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 75, "GetPhoneLanguage", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 76, "Pause", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 77, "d", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 78, "da", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 79, "db", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 80, "dc", METHOD_TYPE_OBJECT },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 81, "enableWifi", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 82, "getManufacture", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 83, "isNeedGcOnFrame", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 84, "isWifiEnabled", METHOD_TYPE_INT },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 85, "launchGLLive", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 86, "launchIGP", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 87, "notifyTrophy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 88, "openBrowser", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 89, "sendAppToBackground", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 90, "sendTrackingInfo", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 91, "onAccuracyChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 92, "onCreate", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 93, "onDestroy", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 94, "onKeyDown", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 95, "onKeyLongPress", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 96, "onKeyUp", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 97, "onLowMemory", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 98, "onPause", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 99, "onRestart", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 100, "onResume", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 101, "onSearchRequested", METHOD_TYPE_BOOLEAN },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 102, "onSensorChanged", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 103, "onStart", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
    { 104, "onStop", METHOD_TYPE_VOID },  // com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian
};

// Candidate methodsInt[] entries -- append into the real methodsInt[] in java.c
static const MethodsInt generated_methodsInt[] = {
    { 0, stub_GLMediaPlayer_getMusicDuration_0 },
    { 1, stub_GLMediaPlayer_getSoundDuration_1 },
    { 2, stub_GLMediaPlayer_getSoundStatus_2 },
    { 4, stub_GLMediaPlayer_isMediaPlaying_4 },
    { 5, stub_GLMediaPlayer_isMusicPlaying_5 },
    { 6, stub_GLMediaPlayer_isSoundLoaded_6 },
    { 31, stub_GLResLoader_getResourceLength_31 },
    { 41, stub_Device_createUniqueCode_41 },
    { 60, stub_Device_getUniqueCode_60 },
    { 75, stub_ShadowGuardian_GetPhoneLanguage_75 },
    { 82, stub_ShadowGuardian_getManufacture_82 },
    { 84, stub_ShadowGuardian_isWifiEnabled_84 },
};

// Candidate methodsVoid[] entries -- append into the real methodsVoid[] in java.c
static const MethodsVoid generated_methodsVoid[] = {
    { 3, stub_GLMediaPlayer_init_3 },
    { 7, stub_GLMediaPlayer_loadMusic_7 },
    { 8, stub_GLMediaPlayer_loadSound_8 },
    { 9, stub_GLMediaPlayer_pauseAllMusic_9 },
    { 10, stub_GLMediaPlayer_pauseAllSounds_10 },
    { 11, stub_GLMediaPlayer_pauseMusic_11 },
    { 12, stub_GLMediaPlayer_pauseSound_12 },
    { 13, stub_GLMediaPlayer_playMusic_13 },
    { 14, stub_GLMediaPlayer_playSound_14 },
    { 15, stub_GLMediaPlayer_resetSound_15 },
    { 16, stub_GLMediaPlayer_resumeMusic_16 },
    { 17, stub_GLMediaPlayer_resumeSound_17 },
    { 18, stub_GLMediaPlayer_setVolume_18 },
    { 19, stub_GLMediaPlayer_stopAllMusic_19 },
    { 20, stub_GLMediaPlayer_stopAllSounds_20 },
    { 21, stub_GLMediaPlayer_stopMusic_21 },
    { 22, stub_GLMediaPlayer_stopSound_22 },
    { 23, stub_GLMediaPlayer_unloadMusic_23 },
    { 24, stub_GLMediaPlayer_unloadSound_24 },
    { 25, stub_GLMediaPlayer_updateSound_25 },
    { 26, stub_GLResLoader_destroy_26 },
    { 33, stub_GLResLoader_init_33 },
    { 35, stub_Device_InitDeviceValues_35 },
    { 43, stub_Device_e_43 },
    { 62, stub_Device_init_62 },
    { 63, stub_Device_a_63 },
    { 65, stub_GameGLSurfaceView_checkEglError_65 },
    { 66, stub_GameGLSurfaceView_onSizeChanged_66 },
    { 68, stub_GameGLSurfaceView_onWindowFocusChanged_68 },
    { 70, stub_GameRenderer_onDrawFrame_70 },
    { 71, stub_GameRenderer_onSurfaceChanged_71 },
    { 72, stub_GameRenderer_onSurfaceCreated_72 },
    { 73, stub_ShadowGuardian_Exit_73 },
    { 76, stub_ShadowGuardian_Pause_76 },
    { 77, stub_ShadowGuardian_d_77 },
    { 81, stub_ShadowGuardian_enableWifi_81 },
    { 85, stub_ShadowGuardian_launchGLLive_85 },
    { 86, stub_ShadowGuardian_launchIGP_86 },
    { 87, stub_ShadowGuardian_notifyTrophy_87 },
    { 88, stub_ShadowGuardian_openBrowser_88 },
    { 89, stub_ShadowGuardian_sendAppToBackground_89 },
    { 90, stub_ShadowGuardian_sendTrackingInfo_90 },
    { 91, stub_ShadowGuardian_onAccuracyChanged_91 },
    { 92, stub_ShadowGuardian_onCreate_92 },
    { 93, stub_ShadowGuardian_onDestroy_93 },
    { 97, stub_ShadowGuardian_onLowMemory_97 },
    { 98, stub_ShadowGuardian_onPause_98 },
    { 99, stub_ShadowGuardian_onRestart_99 },
    { 100, stub_ShadowGuardian_onResume_100 },
    { 102, stub_ShadowGuardian_onSensorChanged_102 },
    { 103, stub_ShadowGuardian_onStart_103 },
    { 104, stub_ShadowGuardian_onStop_104 },
};

// Candidate methodsObject[] entries -- append into the real methodsObject[] in java.c
static const MethodsObject generated_methodsObject[] = {
    { 27, stub_GLResLoader_getRawResource_27 },
    { 28, stub_GLResLoader_getResourceBytes_28 },
    { 29, stub_GLResLoader_getResourceFull_29 },
    { 30, stub_GLResLoader_getResourceFull_30 },
    { 32, stub_GLResLoader_getString_32 },
    { 34, stub_Device_Device_34 },
    { 37, stub_Device_ValidateStringforURL_37 },
    { 38, stub_Device_a_38 },
    { 39, stub_Device_b_39 },
    { 40, stub_Device_c_40 },
    { 42, stub_Device_d_42 },
    { 44, stub_Device_f_44 },
    { 45, stub_Device_getCarrier_45 },
    { 46, stub_Device_getDemoCode_46 },
    { 47, stub_Device_getDevice_47 },
    { 48, stub_Device_getHostName_48 },
    { 49, stub_Device_getIMEI_49 },
    { 51, stub_Device_getLanguage_51 },
    { 52, stub_Device_getLineNumber_52 },
    { 53, stub_Device_getNetworkCountryIso_53 },
    { 54, stub_Device_getNetworkOperator_54 },
    { 55, stub_Device_getNetworkOperatorName_55 },
    { 56, stub_Device_getPhoneModel_56 },
    { 57, stub_Device_getSimCountryIso_57 },
    { 58, stub_Device_getSimOperator_58 },
    { 59, stub_Device_getSimOperatorName_59 },
    { 61, stub_Device_getUserAgent_61 },
    { 64, stub_GameGLSurfaceView_GameGLSurfaceView_64 },
    { 69, stub_GameRenderer_GameRenderer_69 },
    { 78, stub_ShadowGuardian_da_78 },
    { 79, stub_ShadowGuardian_db_79 },
    { 80, stub_ShadowGuardian_dc_80 },
};

// Candidate methodsBoolean[] entries -- append into the real methodsBoolean[] in java.c
static const MethodsBoolean generated_methodsBoolean[] = {
    { 36, stub_Device_IsWifiEnable_36 },
    { 50, stub_Device_getIsRoaming_50 },
    { 67, stub_GameGLSurfaceView_onTouchEvent_67 },
    { 83, stub_ShadowGuardian_isNeedGcOnFrame_83 },
    { 94, stub_ShadowGuardian_onKeyDown_94 },
    { 95, stub_ShadowGuardian_onKeyLongPress_95 },
    { 96, stub_ShadowGuardian_onKeyUp_96 },
    { 101, stub_ShadowGuardian_onSearchRequested_101 },
};

// Candidate methodsLong[] entries -- append into the real methodsLong[] in java.c
static const MethodsLong generated_methodsLong[] = {
    { 74, stub_ShadowGuardian_GetCurrentTime_74 },
};

