/* Auto-generated by psvita-toolkit -- see generated_jni_table.h */
#include <falso_jni/FalsoJNI_Impl.h>
#include "generated_jni_table.h"

// ---- com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer ----
jint stub_GLMediaPlayer_getMusicDuration_0(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.getMusicDuration(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jint stub_GLMediaPlayer_getSoundDuration_1(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.getSoundDuration(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jint stub_GLMediaPlayer_getSoundStatus_2(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.getSoundStatus(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

void stub_GLMediaPlayer_init_3(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.init()V called -- fill in from the real Java impl (jadx).");
}

jint stub_GLMediaPlayer_isMediaPlaying_4(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.isMediaPlaying(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jint stub_GLMediaPlayer_isMusicPlaying_5(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.isMusicPlaying(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

jint stub_GLMediaPlayer_isSoundLoaded_6(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.isSoundLoaded(I)I called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return 0;
}

void stub_GLMediaPlayer_loadMusic_7(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.loadMusic(ILjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_GLMediaPlayer_loadSound_8(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.loadSound(ILjava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);
}

void stub_GLMediaPlayer_pauseAllMusic_9(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.pauseAllMusic()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_pauseAllSounds_10(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.pauseAllSounds()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_pauseMusic_11(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.pauseMusic(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_pauseSound_12(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.pauseSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_playMusic_13(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.playMusic(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_playSound_14(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.playSound(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_resetSound_15(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.resetSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_resumeMusic_16(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.resumeMusic(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_resumeSound_17(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.resumeSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_setVolume_18(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.setVolume(IF)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jfloat arg1 = (jfloat) va_arg(args, double);
}

void stub_GLMediaPlayer_stopAllMusic_19(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.stopAllMusic()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_stopAllSounds_20(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.stopAllSounds()V called -- fill in from the real Java impl (jadx).");
}

void stub_GLMediaPlayer_stopMusic_21(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.stopMusic(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_stopSound_22(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.stopSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_unloadMusic_23(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.unloadMusic(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_unloadSound_24(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.unloadSound(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_GLMediaPlayer_updateSound_25(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLMediaPlayer.updateSound()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader ----
void stub_GLResLoader_destroy_26(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader.destroy()V called -- fill in from the real Java impl (jadx).");
}

jbyteArray stub_GLResLoader_getRawResource_27(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader.getRawResource(ILContext;)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

jbyteArray stub_GLResLoader_getResourceBytes_28(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader.getResourceBytes(Ljava/lang/String;II)[B called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    return NULL;
}

jbyteArray stub_GLResLoader_getResourceFull_29(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader.getResourceFull(I)[B called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    return NULL;
}

jbyteArray stub_GLResLoader_getResourceFull_30(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader.getResourceFull(Ljava/lang/String;)[B called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jint stub_GLResLoader_getResourceLength_31(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader.getResourceLength(Ljava/lang/String;)I called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return 0;
}

jobject stub_GLResLoader_getString_32(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader.getString(ILContext;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_GLResLoader_init_33(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLResLoader.init()V called -- fill in from the real Java impl (jadx).");
}

// ---- com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device ----
jobject stub_Device_Device_34(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.Device()Lpublic; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Device_InitDeviceValues_35(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.InitDeviceValues()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_Device_IsWifiEnable_36(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.IsWifiEnable()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jobject stub_Device_ValidateStringforURL_37(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.ValidateStringforURL(Ljava/lang/String;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jbyteArray stub_Device_a_38(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.a()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Device_b_39(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.b()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Device_c_40(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.c()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jint stub_Device_createUniqueCode_41(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.createUniqueCode()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jbyteArray stub_Device_d_42(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.d()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Device_e_43(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.e(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

jbyteArray stub_Device_f_44(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.f()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getCarrier_45(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getCarrier()Lc; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getDemoCode_46(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getDemoCode()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getDevice_47(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getDevice()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_Device_getHostName_48(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getHostName()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getIMEI_49(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getIMEI()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jboolean stub_Device_getIsRoaming_50(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getIsRoaming()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jobject stub_Device_getLanguage_51(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getLanguage(Ljava/lang/String;)Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    return NULL;
}

jobject stub_Device_getLineNumber_52(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getLineNumber()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getNetworkCountryIso_53(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getNetworkCountryIso()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getNetworkOperator_54(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getNetworkOperator()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getNetworkOperatorName_55(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getNetworkOperatorName()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getPhoneModel_56(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getPhoneModel()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getSimCountryIso_57(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getSimCountryIso()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getSimOperator_58(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getSimOperator()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jobject stub_Device_getSimOperatorName_59(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getSimOperatorName()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jint stub_Device_getUniqueCode_60(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getUniqueCode()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jobject stub_Device_getUserAgent_61(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.getUserAgent()Ljava/lang/String; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_Device_init_62(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.init()V called -- fill in from the real Java impl (jadx).");
}

void stub_Device_a_63(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GLUtils.Device.a(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

// ---- com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView ----
jobject stub_GameGLSurfaceView_GameGLSurfaceView_64(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView.GameGLSurfaceView(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_GameGLSurfaceView_checkEglError_65(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView.checkEglError(Ljava/lang/String;LEGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GameGLSurfaceView_onSizeChanged_66(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView.onSizeChanged(IIII)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
    jint arg3 = (jint) va_arg(args, int);
}

jboolean stub_GameGLSurfaceView_onTouchEvent_67(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView.onTouchEvent(LMotionEvent;)Z called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_GameGLSurfaceView_onWindowFocusChanged_68(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GameGLSurfaceView.onWindowFocusChanged(Z)V called -- fill in from the real Java impl (jadx).");
    jboolean arg0 = (jboolean) va_arg(args, int);
}

// ---- com.gameloft.android.ANMP.GloftSGHP.ML.GameRenderer ----
jobject stub_GameRenderer_GameRenderer_69(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GameRenderer.GameRenderer(LContext;)Lpublic; called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return NULL;
}

void stub_GameRenderer_onDrawFrame_70(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GameRenderer.onDrawFrame(LGL10;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_GameRenderer_onSurfaceChanged_71(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GameRenderer.onSurfaceChanged(LGL10;II)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jint arg1 = (jint) va_arg(args, int);
    jint arg2 = (jint) va_arg(args, int);
}

void stub_GameRenderer_onSurfaceCreated_72(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.GameRenderer.onSurfaceCreated(LGL10;LEGLConfig;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

// ---- com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian ----
void stub_ShadowGuardian_Exit_73(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.Exit()V called -- fill in from the real Java impl (jadx).");
}

jlong stub_ShadowGuardian_GetCurrentTime_74(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.GetCurrentTime()J called -- fill in from the real Java impl (jadx).");
    return 0;
}

jint stub_ShadowGuardian_GetPhoneLanguage_75(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.GetPhoneLanguage()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_ShadowGuardian_Pause_76(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.Pause()V called -- fill in from the real Java impl (jadx).");
}

void stub_ShadowGuardian_d_77(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.d()V called -- fill in from the real Java impl (jadx).");
}

jobject stub_ShadowGuardian_da_78(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.da()LActivity; called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_ShadowGuardian_db_79(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.db()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

jbyteArray stub_ShadowGuardian_dc_80(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.dc()[B called -- fill in from the real Java impl (jadx).");
    return NULL;
}

void stub_ShadowGuardian_enableWifi_81(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.enableWifi(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

jint stub_ShadowGuardian_getManufacture_82(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.getManufacture()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

jboolean stub_ShadowGuardian_isNeedGcOnFrame_83(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.isNeedGcOnFrame()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

jint stub_ShadowGuardian_isWifiEnabled_84(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.isWifiEnabled()I called -- fill in from the real Java impl (jadx).");
    return 0;
}

void stub_ShadowGuardian_launchGLLive_85(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.launchGLLive(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_ShadowGuardian_launchIGP_86(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.launchIGP(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_ShadowGuardian_notifyTrophy_87(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.notifyTrophy(I)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
}

void stub_ShadowGuardian_openBrowser_88(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.openBrowser(Ljava/lang/String;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);
}

void stub_ShadowGuardian_sendAppToBackground_89(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.sendAppToBackground()V called -- fill in from the real Java impl (jadx).");
}

void stub_ShadowGuardian_sendTrackingInfo_90(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.sendTrackingInfo()V called -- fill in from the real Java impl (jadx).");
}

void stub_ShadowGuardian_onAccuracyChanged_91(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onAccuracyChanged(II)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jint arg1 = (jint) va_arg(args, int);
}

void stub_ShadowGuardian_onCreate_92(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onCreate(LBundle;)V called -- fill in from the real Java impl (jadx).");
    jobject arg0 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
}

void stub_ShadowGuardian_onDestroy_93(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onDestroy()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_ShadowGuardian_onKeyDown_94(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onKeyDown(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_ShadowGuardian_onKeyLongPress_95(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onKeyLongPress(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

jboolean stub_ShadowGuardian_onKeyUp_96(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onKeyUp(ILKeyEvent;)Z called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jobject arg1 = (jobject) va_arg(args, jobject);  // best-effort descriptor, confirm the real class path
    return JNI_FALSE;
}

void stub_ShadowGuardian_onLowMemory_97(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onLowMemory()V called -- fill in from the real Java impl (jadx).");
}

void stub_ShadowGuardian_onPause_98(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onPause()V called -- fill in from the real Java impl (jadx).");
}

void stub_ShadowGuardian_onRestart_99(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onRestart()V called -- fill in from the real Java impl (jadx).");
}

void stub_ShadowGuardian_onResume_100(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onResume()V called -- fill in from the real Java impl (jadx).");
}

jboolean stub_ShadowGuardian_onSearchRequested_101(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onSearchRequested()Z called -- fill in from the real Java impl (jadx).");
    return JNI_FALSE;
}

void stub_ShadowGuardian_onSensorChanged_102(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onSensorChanged(I[F)V called -- fill in from the real Java impl (jadx).");
    jint arg0 = (jint) va_arg(args, int);
    jfloatArray arg1 = (jfloatArray) va_arg(args, jobject);
}

void stub_ShadowGuardian_onStart_103(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onStart()V called -- fill in from the real Java impl (jadx).");
}

void stub_ShadowGuardian_onStop_104(jmethodID id, va_list args) {
    fjni_logv_dbg("[JNI STUB] com.gameloft.android.ANMP.GloftSGHP.ML.ShadowGuardian.onStop()V called -- fill in from the real Java impl (jadx).");
}

